Fix: java.lang.IllegalStateException: Can't parcel a recycled bitmap
FATAL EXCEPTION: main
                 Process: kr.co.kadb.cameralibrarykotlinexample, PID: 28018
                 java.lang.RuntimeException: Unable to stop activity {kr.co.kadb.cameralibrarykotlinexample/kr.co.kadb.cameralibrary.presentation.ui.shoot.ShootActivity}: java.lang.IllegalStateException: Can't parcel a recycled bitmap
                 	at android.app.ActivityThread.callActivityOnStop(ActivityThread.java:5905)
                 	at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:5871)
                 	at android.app.ActivityThread.handleStopActivity(ActivityThread.java:5942)
                 	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:240)
                 	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:205)
                 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:177)
                 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:98)
                 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2685)
                 	at android.os.Handler.dispatchMessage(Handler.java:106)
                 	at android.os.Looper.loopOnce(Looper.java:230)
                 	at android.os.Looper.loop(Looper.java:319)
                 	at android.app.ActivityThread.main(ActivityThread.java:8893)
                 	at java.lang.reflect.Method.invoke(Native Method)
                 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
                 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
                 Caused by: java.lang.IllegalStateException: Can't parcel a recycled bitmap
                 	at android.graphics.Bitmap.checkRecycled(Bitmap.java:418)
                 	at android.graphics.Bitmap.writeToParcel(Bitmap.java:2298)
                 	at android.os.Parcel.writeParcelable(Parcel.java:2596)
                 	at android.os.Parcel.writeValue(Parcel.java:2497)
                 	at android.os.Parcel.writeValue(Parcel.java:2374)
                 	at android.os.Parcel.writeArrayMapInternal(Parcel.java:1310)
                 	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1843)
                 	at android.os.Bundle.writeToParcel(Bundle.java:1389)
                 	at android.os.Parcel.writeBundle(Parcel.java:1379)
                 	at android.content.Intent.writeToParcel(Intent.java:12439)
                 	at android.os.Parcel.writeTypedObject(Parcel.java:2215)
                 	at android.app.IActivityClientController$Stub$Proxy.finishActivity(IActivityClientController.java:1649)
                 	at android.app.ActivityClient.finishActivity(ActivityClient.java:179)
                 	at android.app.Activity.finish(Activity.java:7204)
                 	at android.app.Activity.finish(Activity.java:7221)
                 	at kr.co.kadb.cameralibrary.presentation.ui.shoot.ShootFragment.onStop(ShootFragment.kt:159)
                 	at androidx.fragment.app.Fragment.performStop(Fragment.java:3341)
                 	at androidx.fragment.app.FragmentStateManager.stop(FragmentStateManager.java:680)
                 	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:310)
                 	at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:114)
                 	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1455)
                 	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3034)
                 	at androidx.fragment.app.FragmentManager.dispatchStop(FragmentManager.java:2976)
                 	at androidx.fragment.app.FragmentController.dispatchStop(FragmentController.java:307)
                 	at androidx.fragment.app.FragmentActivity.onStop(FragmentActivity.java:373)
                 	at androidx.appcompat.app.AppCompatActivity.onStop(AppCompatActivity.java:257)
                 	at kr.co.kadb.cameralibrary.presentation.widget.util.OBActivity.onStop(OBActivity.kt:183)
                 	at android.app.Instrumentation.callActivityOnStop(Instrumentation.java:1623)
                 	at android.app.Activity.performStop(Activity.java:9198)
                 	at android.app.ActivityThread.callActivityOnStop(ActivityThread.java:5897)
                 	at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:5871)
                 	at android.app.ActivityThread.handleStopActivity(ActivityThread.java:5942)
                 	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:240)
                 	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:205)
                 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:177)
                 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:98)
                 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2685)
                 	at android.os.Handler.dispatchMessage(Handler.java:106)
                 	at android.os.Looper.loopOnce(Looper.java:230)
                 	at android.os.Looper.loop(Looper.java:319)
                 	at android.app.ActivityThread.main(ActivityThread.java:8893)
                 	at java.lang.reflect.Method.invoke(Native Method)
                 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
                 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)